export default {
  title: 'Ads',
  eventTypes: [
    {
      event: 'Global',
      attributes: [
        ['appName', 'Platform'],
        ['playerVersion', 'Player'],
        ['playerName', 'Player'],
        ['contentSrc', 'Content'],
        ['countryCode', 'Geography'],
        ['contentIsLive', 'Content'],
        ['contentTitle', 'Content'],
      ],
    },
    {
      event: 'PageAction',
      eventSelector: { attribute: 'Delivery Type', value: 'Web' },
      attributes: [
        ['adPartner', 'Ad'],
        ['adPosition', 'Ad'],
        ['adTitle', 'Ad'],
        ['adPartner', 'Ad'],
        ['adSrc', 'Ad'],
        ['userAgentName', 'Platform'],
        ['userAgentName', 'Platform'],
        ['userAgentOS', 'Platform'],
        ['userAgentVersion', 'Platform'],
        ['isAd', 'Content'],
        ['asnOrganization', 'Geography'],
        ['city', 'Geography'],
        ['regionCode', 'Geography'],
        ['message', 'Error'],
      ],
    },
    {
      event: 'MobileVideo',
      eventSelector: { attribute: 'Delivery Type', value: 'Mobile' },
      attributes: [
        ['isAd', 'Content'],
        ['asnOrganization', 'Geography'],
        ['city', 'Geography'],
        ['regionCode', 'Geography'],
        ['device', 'Platform'],
        ['deviceGroup', 'Platform'],
        ['deviceType', 'Platform'],
        ['osName', 'Platform'],
        ['osVersion', 'Platform'],
        ['message', 'Error'],
      ],
    },
    {
      event: 'RokuVideo',
      eventSelector: { attribute: 'Delivery Type', value: 'OTT' },
      attributes: [
        ['device', 'Platform'],
        ['deviceGroup', 'Platform'],
        ['deviceType', 'Platform'],
        ['osName', 'Platform'],
        ['osVersion', 'Platform'],
        ['errorMessage', 'Error'],
      ],
    },
  ],
  metrics: [
    {
      title: 'Ads Shown',
      query: {
        nrql: `SELECT count(*) as 'result' from PageAction where actionName = 'AD_START'`,
        lookup: 'result',
      },
      detailConfig: [
        {
          nrql: `SELECT count(*) as 'Ads' from PageAction where actionName = 'AD_START' `,
          columnStart: 1,
          columnEnd: 4,
          chartSize: 'small',
          chartType: 'billboard',
          title: 'Ads Shown',
          useSince: true,
        },
        {
          nrql: `SELECT count(*) as 'Ads' FROM PageAction where actionName = 'AD_START' FACET viewId LIMIT 25`,
          noFacet: true,
          columnStart: 5,
          columnEnd: 12,
          chartSize: 'small',
          chartType: 'bar',
          title: 'Views with most Ads (Click for details)',
          useSince: true,
          click: 'openSession',
        },
      ],
    },
  ],
}