export default {
  title: 'Ingest',
  eventTypes: [
    {
      event: 'Global',
      attributes: [
        ['appName', 'Platform'],
        ['playerVersion', 'Player'],
        ['playerName', 'Player'],
        ['contentSrc', 'Content'],
        ['countryCode', 'Geography'],
        ['contentIsLive', 'Content'],
        ['contentTitle', 'Content'],
      ],
    },
    {
      event: 'PageAction',
      eventSelector: { attribute: 'Delivery Type', value: 'Web' },
      attributes: [
        ['userAgentName', 'Platform'],
        ['userAgentOS', 'Platform'],
        ['userAgentVersion', 'Platform'],
        ['isAd', 'Content'],
        ['asnOrganization', 'Geography'],
        ['city', 'Geography'],
        ['regionCode', 'Geography'],
        ['message', 'Error'],
      ],
    },
    {
      event: 'MobileVideo',
      eventSelector: { attribute: 'Delivery Type', value: 'Mobile' },
      attributes: [
        ['isAd', 'Content'],
        ['asnOrganization', 'Geography'],
        ['city', 'Geography'],
        ['regionCode', 'Geography'],
        ['device', 'Platform'],
        ['deviceGroup', 'Platform'],
        ['deviceType', 'Platform'],
        ['osName', 'Platform'],
        ['osVersion', 'Platform'],
        ['message', 'Error'],
      ],
    },
    {
      event: 'RokuVideo',
      eventSelector: { attribute: 'Delivery Type', value: 'OTT' },
      attributes: [
        ['device', 'Platform'],
        ['deviceGroup', 'Platform'],
        ['deviceType', 'Platform'],
        ['osName', 'Platform'],
        ['osVersion', 'Platform'],
        ['errorMessage', 'Error'],
      ],
    },
  ],
  overviewConfig: [
    {
      nrql: `SELECT sum(provider.executionsStarted.Sum) as 'Starts' FROM AwsStatesStateMachineSample WHERE \`label.aws:cloudformation:logical-id\` = 'IngestWorkflow'`,
      columnStart: 1,
      columnEnd: 3,
      chartSize: 'small',
      chartType: 'billboard',
      title: 'Ingests Initiated',
      useSince: true,
    },
    {
      nrql: `SELECT sum(provider.executionsStarted.Sum) as 'Starts' FROM AwsStatesStateMachineSample WHERE \`label.aws:cloudformation:logical-id\` = 'IngestWorkflow'`,
      columnStart: 4,
      columnEnd: 12,
      chartSize: 'small',
      chartType: 'line',
      title: 'Ingests Initiated',
      useSince: true,
    },
    {
      nrql: `SELECT sum(provider.executionsSucceeded.Sum) as 'Succeeded' FROM AwsStatesStateMachineSample WHERE \`label.aws:cloudformation:logical-id\` = 'IngestWorkflow'`,
      columnStart: 1,
      columnEnd: 3,
      chartSize: 'small',
      chartType: 'billboard',
      title: 'Ingests Succeeded',
      useSince: true,
    },
    {
      nrql: `SELECT sum(provider.executionsStarted.Sum) as 'Succeeded' FROM AwsStatesStateMachineSample WHERE \`label.aws:cloudformation:logical-id\` = 'IngestWorkflow'`,
      columnStart: 4,
      columnEnd: 12,
      chartSize: 'small',
      chartType: 'line',
      title: 'Ingests Succeeded',
      useSince: true,
    },
    {
      nrql: `SELECT sum(provider.executionsFailed.Sum) as 'result' FROM AwsStatesStateMachineSample WHERE \`label.aws:cloudformation:logical-id\` = 'IngestWorkflow'`,
      columnStart: 1,
      columnEnd: 3,
      chartSize: 'small',
      chartType: 'billboard',
      title: 'Ingests Failed',
      useSince: true,
    },
    {
      nrql: `SELECT sum(provider.executionsFailed.Sum) as 'result' FROM AwsStatesStateMachineSample WHERE \`label.aws:cloudformation:logical-id\` = 'IngestWorkflow'`,
      columnStart: 4,
      columnEnd: 12,
      chartSize: 'small',
      chartType: 'line',
      title: 'Ingests Failed',
      useSince: true,
    },
    {
      nrql: `SELECT average(provider.executionTime.Average/1000) as 'Ingest Time (s)' FROM AwsStatesStateMachineSample WHERE \`label.aws:cloudformation:logical-id\` ='IngestWorkflow'`,
      columnStart: 1,
      columnEnd: 3,
      chartSize: 'small',
      chartType: 'billboard',
      title: 'Ingest Time (s)',
      useSince: true,
    },
    {
      nrql: `SELECT average(provider.executionTime.Average/1000) as 'Ingest Time (s)' FROM AwsStatesStateMachineSample WHERE \`label.aws:cloudformation:logical-id\` ='IngestWorkflow'`,
      columnStart: 4,
      columnEnd: 12,
      chartSize: 'small',
      chartType: 'line',
      title: 'Ingests Time (s)',
      useSince: true,
    },
  ],
  metrics: [
    {
      title: 'Ingests Initiated (Count)',
      threshold: {
        critical: 3,
        warning: 5,
        type: 'below',
      },
      invertCompareTo: 'true',
      query: {
        nrql: `SELECT sum(provider.executionsStarted.Sum) as 'result' FROM AwsStatesStateMachineSample WHERE \`label.aws:cloudformation:logical-id\` = 'IngestWorkflow'`,
        lookup: 'result',
      },
      detailConfig: [
        {
          nrql: `SELECT sum(provider.executionsStarted.Sum) as 'Executions' FROM AwsStatesStateMachineSample WHERE \`label.aws:cloudformation:logical-id\` = 'IngestWorkflow'`,
          columnStart: 1,
          columnEnd: 3,
          chartSize: 'medium',
          chartType: 'billboard',
          title: 'Ingests Initiated',
          useSince: true,
        },
        {
          nrql: `SELECT sum(provider.executionsStarted.Sum) as 'Executions' FROM AwsStatesStateMachineSample WHERE \`label.aws:cloudformation:logical-id\` = 'IngestWorkflow'`,
          columnStart: 4,
          columnEnd: 12,
          chartSize: 'medium',
          chartType: 'line',
          title: 'Ingests Initiated',
          useSince: true,
        }
      ],
    },
    {
      title: 'Ingests Succeeded (Count)',
      threshold: {
        critical: 3,
        warning: 5,
        type: 'below',
      },
      invertCompareTo: 'true',
      query: {
        nrql: `SELECT sum(provider.executionsSucceeded.Sum) as 'result' FROM AwsStatesStateMachineSample WHERE \`label.aws:cloudformation:logical-id\` = 'IngestWorkflow'`,
        lookup: 'result',
      },
      detailConfig: [
        {
          nrql: `SELECT sum(provider.executionsSucceeded.Sum) as 'Succeeded' FROM AwsStatesStateMachineSample WHERE \`label.aws:cloudformation:logical-id\` = 'IngestWorkflow'`,
          columnStart: 1,
          columnEnd: 3,
          chartSize: 'medium',
          chartType: 'billboard',
          title: 'Ingests Succeeded',
          useSince: true,
        },
        {
          nrql: `SELECT sum(provider.executionsStarted.Sum) as 'Succeeded' FROM AwsStatesStateMachineSample WHERE \`label.aws:cloudformation:logical-id\` = 'IngestWorkflow'`,
          columnStart: 4,
          columnEnd: 12,
          chartSize: 'medium',
          chartType: 'line',
          title: 'Ingests Succeeded',
          useSince: true,
        },
      ],
    },
    {
      title: 'Ingests Failed (Count)',
      threshold: {
        critical: 1,
        warning: .5,
      },
      query: {
        nrql: `SELECT sum(provider.executionsFailed.Sum) as 'result' FROM AwsStatesStateMachineSample WHERE \`label.aws:cloudformation:logical-id\` = 'IngestWorkflow'`,
        lookup: 'result',
      },
      detailConfig: [
        {
          nrql: `SELECT sum(provider.executionsFailed.Sum) as 'result' FROM AwsStatesStateMachineSample WHERE \`label.aws:cloudformation:logical-id\` = 'IngestWorkflow'`,
          columnStart: 1,
          columnEnd: 3,
          chartSize: 'small',
          chartType: 'billboard',
          title: 'Ingests Failed',
          useSince: true,
        },
        {
          nrql: `SELECT sum(provider.executionsFailed.Sum) as 'result' FROM AwsStatesStateMachineSample WHERE \`label.aws:cloudformation:logical-id\` = 'IngestWorkflow'`,
          columnStart: 4,
          columnEnd: 12,
          chartSize: 'small',
          chartType: 'line',
          title: 'Ingests Failed',
          useSince: true,
        },
      ],
    },
    {
      title: 'Ingest Time (s)',
      threshold: {
        critical: 20,
        warning: 10,
      },
      query: {
        nrql: `SELECT average(provider.executionTime.Average/1000) as 'result' FROM AwsStatesStateMachineSample WHERE \`label.aws:cloudformation:logical-id\` ='IngestWorkflow'`,
        lookup: 'result',
      },
      detailConfig: [
        {
          nrql: `SELECT average(provider.executionTime.Average/1000) as 'Ingest Time (s)' FROM AwsStatesStateMachineSample WHERE \`label.aws:cloudformation:logical-id\` ='IngestWorkflow'`,
          columnStart: 1,
          columnEnd: 3,
          chartSize: 'medium',
          chartType: 'billboard',
          title: 'Ingest Time (s)',
          useSince: true,
        },
        {
          nrql: `SELECT average(provider.executionTime.Average/1000) as 'Ingest Time (s)' FROM AwsStatesStateMachineSample WHERE \`label.aws:cloudformation:logical-id\` ='IngestWorkflow'`,
          columnStart: 4,
          columnEnd: 12,
          chartSize: 'medium',
          chartType: 'line',
          title: 'Ingests Time (s)',
          useSince: true,
        },
      ],
    },
    {
      title: 'Ingest Failure Ratio (%)',
      threshold: {
        critical: 10,
        warning: 5,
      },
      query: {
        nrql: `FROM AwsStatesStateMachineSample SELECT sum(provider.executionsFailed.Sum) / sum(provider.executionsStarted.Sum) * 100 as 'result' WHERE \`label.aws:cloudformation:logical-id\` = 'IngestWorkflow'`,
        lookup: 'result',
      },
      detailConfig: [
        {
          nrql: `FROM PageAction, MobileVideo, RokuVideo SELECT filter(sum(timeSinceBufferBegin), WHERE actionName = 'CONTENT_BUFFER_END' and contentPlayhead > 0) / filter(sum(playtimeSinceLastEvent), WHERE contentPlayhead is not null) * 100 as '%' `,
          columnStart: 1,
          columnEnd: 3,
          chartSize: 'small',
          chartType: 'billboard',
          title: 'Rebuffering Ratio',
          useSince: true,
        },
        {
          nrql: `FROM PageAction, MobileVideo, RokuVideo SELECT sum(timeSinceBufferBegin)/1000 as 'Total Buffering' WHERE actionName = 'CONTENT_BUFFER_END' and contentPlayhead > 0 FACET viewId LIMIT 25 `,
          noFacet: true,
          columnStart: 4,
          columnEnd: 12,
          chartSize: 'small',
          chartType: 'bar',
          title: 'Sessions with most Rebuffering, Seconds (Click for details)',
          useSince: true,
          click: 'openSession',
        },
        {
          nrql: `FROM PageAction, MobileVideo, RokuVideo SELECT filter(sum(timeSinceBufferBegin), WHERE actionName = 'CONTENT_BUFFER_END' and contentPlayhead > 0) / filter(sum(playtimeSinceLastEvent), WHERE contentPlayhead is not null) * 100 as '%' TIMESERIES MAX `,
          facets: `deviceType`,
          columnStart: 1,
          columnEnd: 12,
          chartSize: 'small',
          chartType: 'area',
          title: 'Rebuffering Ratio by Device Type',
          useSince: true,
        },
        {
          nrql: `FROM PageAction, MobileVideo, RokuVideo SELECT percentile(timeSinceBufferBegin/1000, 50) as 'seconds', percentile(timeSinceBufferBegin/1000, 90) as 'seconds', percentile(timeSinceBufferBegin/1000, 95) as 'seconds', percentile(timeSinceBufferBegin/1000, 99) as 'seconds' WHERE actionName = 'CONTENT_BUFFER_END' and contentPlayhead = 0 `,
          columnStart: 1,
          columnEnd: 4,
          chartSize: 'medium',
          chartType: 'billboard',
          title: 'Initial Buffer Time',
          useSince: true,
        },
        {
          nrql: `FROM PageAction, MobileVideo, RokuVideo SELECT percentile(timeSinceBufferBegin/1000, 50) as 'seconds', percentile(timeSinceBufferBegin/1000, 90) as 'seconds', percentile(timeSinceBufferBegin/1000, 95) as 'seconds', percentile(timeSinceBufferBegin/1000, 99) as 'seconds' WHERE actionName = 'CONTENT_BUFFER_END' and contentPlayhead = 0 TIMESERIES MAX `,
          facets: '',
          columnStart: 5,
          columnEnd: 12,
          chartSize: 'medium',
          chartType: 'area',
          title: 'Initial Buffer Time',
          useSince: true,
        },
      ],
    },
  ],
}
