import VideoOverview from '../components/metric-detail/VideoOverview'
import VideoDetail from '../components/metric-detail/VIdeoDetail'

export default {
  title: 'Video',
  eventTypes: [
    {
      event: 'Global',
      attributes: [
        ['appName', 'Platform'],
        ['playerVersion', 'Player'],
        ['playerName', 'Player'],
        ['contentSrc', 'Content'],
        ['countryCode', 'Content'],
        ['contentIsLive', 'Content'],
        ['contentTitle', 'Content'],
      ],
    },
    {
      event: 'PageAction',
      eventSelector: { attribute: 'Delivery Type', value: 'Web' },
      attributes: [
        ['userAgentName', 'Platform'],
        ['userAgentOS', 'Platform'],
        ['userAgentVersion', 'Platform'],
        ['isAd', 'Content'],
        ['asnOrganization', 'Geography'],
        ['city', 'Geography'],
        ['regionCode', 'Geography'],
        ['message', 'Error'],
      ],
    },
    {
      event: 'MobileVideo',
      eventSelector: { attribute: 'Delivery Type', value: 'Mobile' },
      attributes: [
        ['isAd', 'Content'],
        ['asnOrganization', 'Geography'],
        ['city', 'Geography'],
        ['regionCode', 'Geography'],
        ['device', 'Platform'],
        ['deviceGroup', 'Platform'],
        ['deviceType', 'Platform'],
        ['osName', 'Platform'],
        ['osVersion', 'Platform'],
        ['message', 'Error'],
      ],
    },
    {
      event: 'RokuVideo',
      eventSelector: { attribute: 'Delivery Type', value: 'OTT' },
      attributes: [
        ['device', 'Platform'],
        ['deviceGroup', 'Platform'],
        ['deviceType', 'Platform'],
        ['osName', 'Platform'],
        ['osVersion', 'Platform'],
        ['errorMessage', 'Error'],
      ],
    },
  ],
  overview: (props, filters, facets) => {
    return (
      <VideoOverview
        accountId={props.accountId}
        duration={props.duration}
        filters={filters}
        facets={facets}
      />
    )
  },
  detailView: (props, filters, facets) => {
    return (
      <VideoDetail
        accountId={props.accountId}
        duration={props.duration}
        stack={props.stack}
        activeMetric={props.activeMetric}
        filters={filters}
        facets={facets}
      />
    )
  },
  metrics: [
    {
      title: 'Player Ready (Seconds)',
      threshold: {
        critical: 10,
        warning: 5,
      },
      query: {
        nrql: `SELECT percentile(timeSinceLoad, 50) as 'percentile' FROM PageAction, MobileVideo, RokuVideo WHERE actionName = 'PLAYER_READY'`,
        lookup: 'percentile',
      },
      detailConfig: [
        {
          nrql: `SELECT average(timeSinceLoad) as 'Player Ready Time' FROM PageAction, MobileVideo, RokuVideo WHERE actionName = 'PLAYER_READY' `,
          facets: `deviceType`,
          columnStart: 1,
          columnEnd: 2,
          chartSize: 'medium',
          chartType: 'billboard',
          title: 'Player Ready Time (50%)',
          useSince: true,
        },
        {
          nrql: `SELECT average(timeSinceLoad) as 'Player Ready Time' FROM PageAction, MobileVideo, RokuVideo WHERE actionName = 'PLAYER_READY' TIMESERIES MAX `,
          columnStart: 3,
          columnEnd: 7,
          chartSize: 'medium',
          chartType: 'scatter',
          title: 'Player Ready Time (Average)',
          useSince: true,
        },
        {
          nrql: `FROM PageAction, MobileVideo, RokuVideo SELECT percentile(timeSinceLoad, 50) WHERE actionName = 'PLAYER_READY' TIMESERIES auto `,
          facets: `deviceType`,
          columnStart: 8,
          columnEnd: 12,
          chartSize: 'medium',
          chartType: 'area',
          title: 'Player Ready Time by Device Type',
          useSince: true,
        },
        {
          nrql: `SELECT average(timeSinceLoad) as 'Time To Player Ready (Average)' FROM PageAction, MobileVideo, RokuVideo WHERE actionName = 'PLAYER_READY' FACET viewId `,
          noFacet: true,
          columnStart: 1,
          columnEnd: 6,
          chartSize: 'medium',
          chartType: 'bar',
          title: 'Average Player Ready Time by View',
          useSince: true,
          click: 'openSession',
        },
        {
          nrql: `FROM PageAction, MobileVideo, RokuVideo SELECT histogram(timeSinceLoad, buckets: 10, width: 20) WHERE actionName = 'PLAYER_READY' `,
          facets: `deviceType`,
          columnStart: 7,
          columnEnd: 12,
          chartSize: 'medium',
          chartType: 'heatmap',
          title: 'Player Ready Time by Device Type',
          useSince: true,
        },
      ],
    },
    {
      title: 'Video Start Failure (%)',
      query: {
        nrql: `FROM PageAction, RokuVideo, MobileVideo SELECT filter(count(*), where actionName = 'CONTENT_ERROR' and contentPlayhead = 0) / filter(count(*), where actionName = 'CONTENT_REQUEST') * 100 as 'result'`,
        lookup: 'result',
      },
      detailConfig: [
        {
          nrql: `FROM PageAction, RokuVideo, MobileVideo SELECT filter(count(*), where actionName = 'CONTENT_ERROR' and contentPlayhead = 0) / filter(count(*), where actionName = 'CONTENT_REQUEST') * 100 as '%' `,
          columnStart: 1,
          columnEnd: 3,
          chartSize: 'small',
          chartType: 'billboard',
          title: 'Video Start Failure Ratio',
          useSince: true,
        },
        {
          nrql: `FROM PageAction SELECT filter(count(*), where actionName = 'CONTENT_ERROR' and contentPlayhead = 0) / filter(count(*), where actionName = 'CONTENT_REQUEST') * 100 as '%' TIMESERIES MAX `,
          columnStart: 4,
          columnEnd: 12,
          chartSize: 'small',
          chartType: 'area',
          title: 'Video Start Failure Ratio',
          useSince: true,
        },
        {
          nrql: `FROM PageAction, RokuVideo, MobileVideo SELECT count(*) where actionName = 'CONTENT_ERROR' and contentPlayhead = 0 facet viewId `,
          noFacet: 'true',
          columnStart: 1,
          columnEnd: 6,
          chartSize: 'large',
          chartType: 'bar',
          title: 'Views with Video Start Failures',
          useSince: true,
          click: 'openSession',
        },
        {
          nrql: `FROM PageAction, RokuVideo, MobileVideo SELECT count(*) where actionName = 'CONTENT_ERROR' and contentPlayhead = 0 `,
          facets: 'message',
          columnStart: 7,
          columnEnd: 12,
          chartSize: 'large',
          chartType: 'bar',
          title: 'Video Start Failures by Error Message',
          useSince: true,
        },
      ],
    },
    {
      title: 'In-Stream Error Ratio (%)',
      threshold: {
        critical: 1,
        warning: 0.5,
      },
      query: {
        nrql: `FROM PageAction, RokuVideo, MobileVideo SELECT filter(count(*), where actionName = 'CONTENT_ERROR' and contentPlayhead > 0) / filter(count(*), where actionName = 'CONTENT_REQUEST') * 100 as 'result'`,
        lookup: 'result',
      },
      detailConfig: [
        {
          nrql: `FROM PageAction, RokuVideo, MobileVideo SELECT filter(count(*), where actionName = 'CONTENT_ERROR' and contentPlayhead > 0) / filter(count(*), where actionName = 'CONTENT_REQUEST') * 100 as '%' `,
          columnStart: 1,
          columnEnd: 3,
          chartSize: 'small',
          chartType: 'billboard',
          title: 'In-Stream Error Ratio',
          useSince: true,
        },
        {
          nrql: `FROM PageAction SELECT filter(count(*), where actionName = 'CONTENT_ERROR' and contentPlayhead > 0) / filter(count(*), where actionName = 'CONTENT_REQUEST') * 100 as '%' TIMESERIES MAX `,
          facets: 'deviceType',
          columnStart: 4,
          columnEnd: 12,
          chartSize: 'small',
          chartType: 'area',
          title: 'In-Stream Error Ratio',
          useSince: true,
        },
        {
          nrql: `FROM PageAction, RokuVideo, MobileVideo SELECT count(*) where actionName = 'CONTENT_ERROR' and contentPlayhead > 0 facet viewId `,
          noFacet: true,
          columnStart: 1,
          columnEnd: 6,
          chartSize: 'large',
          chartType: 'bar',
          title: 'Views with Errors',
          useSince: true,
          click: 'openSession',
        },
        {
          nrql: `FROM PageAction, RokuVideo, MobileVideo SELECT count(*) where actionName = 'CONTENT_ERROR' and contentPlayhead > 0 `,
          facets: 'message',
          columnStart: 7,
          columnEnd: 12,
          chartSize: 'large',
          chartType: 'bar',
          title: 'In-Stream Errors by Message',
          useSince: true,
        },
      ],
    },
    {
      title: 'Join Time Since Requested (Median)',
      threshold: {
        critical: 5,
        warning: 3,
      },
      query: {
        nrql: `SELECT percentile(timeSinceRequested/1000, 50) as 'percentile' FROM PageAction, MobileVideo, RokuVideo WHERE actionName = 'CONTENT_START'`,
        lookup: 'percentile',
      },
      detailConfig: [
        {
          nrql: `FROM PageAction, RokuVideo, MobileVideo SELECT percentile(timeSinceLoad, 50) as 'seconds' WHERE actionName = 'CONTENT_START' `,
          columnStart: 1,
          columnEnd: 3,
          chartSize: 'small',
          chartType: 'billboard',
          title: 'Join Time - Aggregate, Content',
          useSince: true,
        },
        {
          nrql: `FROM PageAction, RokuVideo, MobileVideo SELECT percentile(timeSinceLoad, 50) as 'seconds' WHERE actionName = 'CONTENT_START' TIMESERIES MAX `,
          facets: 'deviceType',
          columnStart: 4,
          columnEnd: 12,
          chartSize: 'small',
          chartType: 'area',
          title: 'Join Time - Aggregate, Content',
          useSince: true,
        },
        {
          nrql: `FROM PageAction, RokuVideo, MobileVideo SELECT percentile(timeSinceRequested/1000, 50) as 'seconds' WHERE actionName = 'CONTENT_START'`,
          columnStart: 1,
          columnEnd: 3,
          chartSize: 'small',
          chartType: 'billboard',
          title: 'Join Time Since Requested',
          useSince: true,
        },
        {
          nrql: `FROM PageAction, RokuVideo, MobileVideo SELECT percentile(timeSinceRequested/1000, 50) as 'seconds' WHERE actionName = 'CONTENT_START' TIMESERIES MAX `,
          facets: 'deviceType',
          columnStart: 4,
          columnEnd: 12,
          chartSize: 'small',
          chartType: 'area',
          title: 'Join Time Since Requested',
          useSince: true,
        },
        {
          nrql: `FROM PageAction, MobileVideo, RokuVideo SELECT filter(percentile(timeSinceLastAd/1000,50), WHERE actionName = 'CONTENT_START') + filter(percentile(timeSinceRequested/1000, 50), WHERE actionName = 'AD_REQUEST') as 'seconds (50%)'`,
          columnStart: 1,
          columnEnd: 3,
          chartSize: 'small',
          chartType: 'billboard',
          title: 'Join Time - Content without Ads',
          useSince: true,
        },
        {
          nrql: `FROM PageAction, MobileVideo, RokuVideo SELECT filter(percentile(timeSinceLastAd/1000,50), WHERE actionName = 'CONTENT_START') + filter(percentile(timeSinceRequested/1000, 50), WHERE actionName = 'AD_REQUEST') as 'seconds' TIMESERIES MAX `,
          facets: 'deviceType',
          columnStart: 4,
          columnEnd: 12,
          chartSize: 'small',
          chartType: 'area',
          title: 'Join Time - Content without Ads',
          useSince: true,
        },
        {
          nrql: `FROM PageAction, MobileVideo, RokuVideo SELECT percentile(timeSinceRequested/1000,50) as 'seconds' where actionName = 'AD_START' and adPosition = 'pre'`,
          columnStart: 1,
          columnEnd: 3,
          chartSize: 'small',
          chartType: 'billboard',
          title: 'Join Time - Pre Roll Ad',
          useSince: true,
        },
        {
          nrql: `FROM PageAction, MobileVideo, RokuVideo SELECT percentile(timeSinceRequested/1000,50) as 'seconds' where actionName = 'AD_START' and adPosition = 'pre' TIMESERIES MAX `,
          facets: 'deviceType',
          columnStart: 4,
          columnEnd: 12,
          chartSize: 'small',
          chartType: 'area',
          title: 'Join Time - Pre Roll Ad',
          useSince: true,
        },
        {
          nrql: `SELECT average(timeSinceRequested/1000) as 'Time To First Frame (Average)' FROM PageAction, MobileVideo, RokuVideo WHERE actionName = 'CONTENT_START' FACET viewId`,
          noFacet: true,
          columnStart: 1,
          columnEnd: 12,
          chartSize: 'medium',
          chartType: 'bar',
          title: 'Views (Average Join Time Since Requested)',
          useSince: true,
          click: 'openSession',
        },
      ],
    },
    {
      title: 'Rebuffering Ratio (%)',
      query: {
        nrql: `FROM PageAction, MobileVideo, RokuVideo SELECT filter(sum(timeSinceBufferBegin), WHERE actionName = 'CONTENT_BUFFER_END' and contentPlayhead > 0) / filter(sum(playtimeSinceLastEvent), WHERE contentPlayhead is not null) * 100 as 'result'`,
        lookup: 'result',
      },
      detailConfig: [
        {
          nrql: `FROM PageAction, MobileVideo, RokuVideo SELECT filter(sum(timeSinceBufferBegin), WHERE actionName = 'CONTENT_BUFFER_END' and contentPlayhead > 0) / filter(sum(playtimeSinceLastEvent), WHERE contentPlayhead is not null) * 100 as '%' `,
          columnStart: 1,
          columnEnd: 2,
          chartSize: 'medium',
          chartType: 'billboard',
          title: 'Rebuffering Ratio',
          useSince: true,
        },
        {
          nrql: `FROM PageAction, MobileVideo, RokuVideo SELECT filter(sum(timeSinceBufferBegin), WHERE actionName = 'CONTENT_BUFFER_END' and contentPlayhead > 0) / filter(sum(playtimeSinceLastEvent), WHERE contentPlayhead is not null) * 100 as '%' TIMESERIES MAX `,
          facets: `deviceType`,
          columnStart: 3,
          columnEnd: 7,
          chartSize: 'medium',
          chartType: 'area',
          title: 'Rebuffering Ratio by Device Type',
          useSince: true,
        },
        {
          nrql: `FROM PageAction, MobileVideo, RokuVideo SELECT sum(timeSinceBufferBegin)/1000 as 'Total Buffering' WHERE actionName = 'CONTENT_BUFFER_END' and contentPlayhead > 0 FACET viewId `,
          noFacet: true,
          columnStart: 8,
          columnEnd: 12,
          chartSize: 'medium',
          chartType: 'bar',
          title: 'Sessions with most Rebuffering (Seconds)',
          useSince: true,
          click: 'openSession',
        },
        {
          nrql: `FROM PageAction, MobileVideo, RokuVideo SELECT percentile(timeSinceBufferBegin/1000, 50) as 'seconds', percentile(timeSinceBufferBegin/1000, 90) as 'seconds', percentile(timeSinceBufferBegin/1000, 95) as 'seconds', percentile(timeSinceBufferBegin/1000, 99) as 'seconds' WHERE actionName = 'CONTENT_BUFFER_END' and contentPlayhead = 0 `,
          columnStart: 1,
          columnEnd: 4,
          chartSize: 'medium',
          chartType: 'billboard',
          title: 'Initial Buffer Time',
          useSince: true,
        },
        {
          nrql: `FROM PageAction, MobileVideo, RokuVideo SELECT percentile(timeSinceBufferBegin/1000, 50) as 'seconds', percentile(timeSinceBufferBegin/1000, 90) as 'seconds', percentile(timeSinceBufferBegin/1000, 95) as 'seconds', percentile(timeSinceBufferBegin/1000, 99) as 'seconds' WHERE actionName = 'CONTENT_BUFFER_END' and contentPlayhead = 0 TIMESERIES MAX `,
          facets: '',
          columnStart: 5,
          columnEnd: 12,
          chartSize: 'medium',
          chartType: 'area',
          title: 'Initial Buffer Time',
          useSince: true,
        },
      ],
    },
    {
      title: 'Average Bitrate (mbps)',
      query: {
        nrql: `FROM PageAction, RokuVideo, MobileVideo SELECT average(contentBitrate)/1000000 as 'result' where contentBitrate is not null `,
        lookup: 'result',
      },
      detailConfig: [
        {
          nrql: `FROM PageAction, RokuVideo, MobileVideo SELECT percentile(contentBitrate, 50)/1000000, percentile(contentBitrate, 90)/1000000, percentile(contentBitrate, 95)/1000000, percentile(contentBitrate, 99)/1000000 where contentBitrate is not null `,
          columnStart: 1,
          columnEnd: 4,
          chartSize: 'medium',
          chartType: 'billboard',
          title: 'Content Bitrate Percentile',
          useSince: true,
        },
        {
          nrql: `FROM PageAction, RokuVideo, MobileVideo SELECT percentile(contentBitrate, 50)/1000000, percentile(contentBitrate, 90)/1000000, percentile(contentBitrate, 95)/1000000, percentile(contentBitrate, 99)/1000000 where contentBitrate is not null TIMESERIES MAX `,
          columnStart: 5,
          columnEnd: 12,
          chartSize: 'medium',
          chartType: 'area',
          title: 'Content Bitrate Percentile',
          useSince: true,
        },
        {
          nrql: `FROM PageAction, RokuVideo, MobileVideo SELECT percentile(contentBitrate, 50)/1000000 as '', percentile(contentBitrate, 90)/1000000 as '', percentile(contentBitrate, 95)/1000000 as '', percentile(contentBitrate, 99)/1000000 as '' where contentBitrate is not null  FACET eventType() `,
          noFacet: true,
          columnStart: 1,
          columnEnd: 6,
          chartSize: 'medium',
          chartType: 'billboard',
          title: 'Content Bitrate Percentile by Event Type',
          useSince: true,
        },
        {
          nrql: `FROM PageAction, RokuVideo, MobileVideo SELECT average(contentBitrate)/1000000 as 'mbps' where contentBitrate is not null facet viewId `,
          noFacet: true,
          columnStart: 7,
          columnEnd: 12,
          chartSize: 'medium',
          chartType: 'bar',
          title: 'Average Content Bitrate by View',
          useSince: true,
          click: 'openSession',
        },
      ],
    },
    {
      title: 'Interruption Ratio (%)',
      query: {
        nrql: `FROM PageAction, MobileVideo, RokuVideo SELECT filter(count(*), WHERE actionName = 'CONTENT_BUFFER_START' and contentPlayhead > 0) / filter(count(*), WHERE actionName IN ('CONTENT_START', 'CONTENT_NEXT')) * 100 as 'result'`,
        lookup: 'result',
      },
      detailConfig: [
        {
          nrql: `FROM PageAction, MobileVideo, RokuVideo SELECT filter(count(*), WHERE actionName = 'CONTENT_BUFFER_START' and contentPlayhead > 0) / filter(count(*), WHERE actionName IN ('CONTENT_START', 'CONTENT_NEXT')) * 100 as '%' `,
          columnStart: 1,
          columnEnd: 3,
          chartSize: 'medium',
          chartType: 'billboard',
          title: 'Interruption Ratio',
          useSince: true,
        },
        {
          nrql: `FROM PageAction, MobileVideo, RokuVideo SELECT filter(count(*), WHERE actionName = 'CONTENT_BUFFER_START' and contentPlayhead > 0) / filter(count(*), WHERE actionName IN ('CONTENT_START', 'CONTENT_NEXT')) * 100 as '%' timeseries MAX `,
          facets: `deviceType`,
          columnStart: 4,
          columnEnd: 12,
          chartSize: 'medium',
          chartType: 'line',
          title: 'Interruption Ratio',
          useSince: true,
        },
        {
          nrql: `FROM PageAction, MobileVideo, RokuVideo SELECT count(*) WHERE actionName = 'CONTENT_BUFFER_START' and contentPlayhead > 0 FACET viewId `,
          noFacet: true,
          columnStart: 1,
          columnEnd: 12,
          chartSize: 'medium',
          chartType: 'bar',
          title: 'Views with Interruptions',
          useSince: true,
          click: 'openSession',
        },
      ],
    },
    {
      title: 'Rendition Change Rate',
      query: {
        nrql: `SELECT filter(count(*), WHERE actionName = 'CONTENT_RENDITION_CHANGE') / filter(count(*), WHERE actionName = 'CONTENT_START') AS 'result' FROM PageAction, MobileVideo, RokuVideo`,
        lookup: 'result',
      },
      detailConfig: [
        {
          nrql: `FROM PageAction, RokuVideo, MobileVideo SELECT count(*) as 'shifts' where actionName = 'CONTENT_RENDITION_CHANGE' `,
          facets: 'shift',
          columnStart: 1,
          columnEnd: 3,
          chartSize: 'small',
          chartType: 'pie',
          title: 'Content Rendition Changes by Shift',
          useSince: true,
        },
        {
          nrql: `FROM PageAction, RokuVideo, MobileVideo SELECT count(*) as 'shifts' where actionName = 'CONTENT_RENDITION_CHANGE'  timeseries MAX `,
          facets: `shift`,
          columnStart: 4,
          columnEnd: 12,
          chartSize: 'small',
          chartType: 'area',
          title: 'Content Rendition Changes by Shift',
          useSince: true,
        },
        {
          nrql: `FROM PageAction, RokuVideo, MobileVideo SELECT count(*) as 'shifts' where actionName = 'CONTENT_RENDITION_CHANGE' `,
          facets: 'contentTitle',
          columnStart: 1,
          columnEnd: 3,
          chartSize: 'small',
          chartType: 'pie',
          title: 'Content Rendition Changes by Title',
          useSince: true,
        },
        {
          nrql: `FROM PageAction, RokuVideo, MobileVideo SELECT count(*) as 'shifts' where actionName = 'CONTENT_RENDITION_CHANGE'  timeseries MAX `,
          facets: `contentTitle`,
          columnStart: 4,
          columnEnd: 12,
          chartSize: 'small',
          chartType: 'area',
          title: 'Content Rendition Changes by Title',
          useSince: true,
        },
        {
          nrql: `FROM PageAction, MobileVideo, RokuVideo SELECT count(*) WHERE actionName = 'CONTENT_RENDITION_CHANGE' and contentPlayhead > 0 FACET viewId `,
          noFacet: true,
          columnStart: 1,
          columnEnd: 12,
          chartSize: 'medium',
          chartType: 'bar',
          title: 'Views with Rendition Changes',
          useSince: true,
          click: 'openSession',
        },
      ],
    },
  ],
}
