import { USER_IDENTIFIER, VIDEO_EVENTS } from './constants'

export default {
  title: 'Audience',
  eventTypes: [
    {
      event: 'Global',
      attributes: [
        ['appName', 'Platform'],
        ['playerVersion', 'Player'],
        ['playerName', 'Player'],
        ['contentSrc', 'Content'],
        ['countryCode', 'Geography'],
        ['contentIsLive', 'Content'],
        ['contentTitle', 'Content'],
      ],
    },
    {
      event: 'PageAction',
      eventSelector: { attribute: 'Delivery Type', value: 'Web' },
      attributes: [
        ['userAgentName', 'Platform'],
        ['userAgentOS', 'Platform'],
        ['userAgentVersion', 'Platform'],
        ['isAd', 'Content'],
        ['asnOrganization', 'Geography'],
        ['city', 'Geography'],
        ['regionCode', 'Geography'],
        ['message', 'Error'],
      ],
    },
    {
      event: 'MobileVideo',
      eventSelector: { attribute: 'Delivery Type', value: 'Mobile' },
      attributes: [
        ['isAd', 'Content'],
        ['asnOrganization', 'Geography'],
        ['city', 'Geography'],
        ['regionCode', 'Geography'],
        ['device', 'Platform'],
        ['deviceGroup', 'Platform'],
        ['deviceType', 'Platform'],
        ['osName', 'Platform'],
        ['osVersion', 'Platform'],
        ['message', 'Error'],
      ],
    },
    {
      event: 'RokuVideo',
      eventSelector: { attribute: 'Delivery Type', value: 'OTT' },
      attributes: [
        ['device', 'Platform'],
        ['deviceGroup', 'Platform'],
        ['deviceType', 'Platform'],
        ['osName', 'Platform'],
        ['osVersion', 'Platform'],
        ['errorMessage', 'Error'],
      ],
    },
    {
      event: 'BrowserVideo',
      eventSelector: { attribute: 'Delivery Type', value: 'Web' },
      attributes: [
        ['userAgentName', 'Platform'],
        ['userAgentOS', 'Platform'],
        ['userAgentVersion', 'Platform'],
        ['isAd', 'Content'],
        // ['asnOrganization', 'Geography'],
        // ['city', 'Geography'],
        // ['regionCode', 'Geography'],
        ['message', 'Error'],
      ],
    },
  ],
  metrics: [
    {
      title: 'Play Attempts',
      invertCompareTo: 'true',
      query: {
        nrql: `SELECT count(*) as 'result' FROM ${VIDEO_EVENTS} where actionName = 'CONTENT_REQUEST' `,
        lookup: 'result',
      },
      detailDashboardId: 'Audience-Plays-Detail',
    },
    {
      title: 'Plays',
      invertCompareTo: 'true',
      query: {
        nrql: `SELECT count(*) as 'result' FROM ${VIDEO_EVENTS} where actionName = 'CONTENT_START' `,
        lookup: 'result',
      },
      detailDashboardId: 'Audience-Plays-Detail',
    },
    {
      title: 'Peak Concurrent Plays',
      invertCompareTo: 'true',
      query: {
        nrql: `SELECT uniquecount(viewId) as 'result' FROM ${VIDEO_EVENTS} where PageAction.actionName NOT IN ('PLAYER_READY') AND totalPlaytime > 1000`,
        lookup: 'result',
      },
      detailDashboardId: 'Audience-Plays-Detail',
    },
    {
      title: 'Total Playtime (minutes)',
      invertCompareTo: 'true',
      query: {
        nrql: `SELECT sum(playtimeSinceLastEvent)/60000 as 'result' from ${VIDEO_EVENTS}`,
        lookup: 'result',
      },
      detailDashboardId: 'Audience-Plays-Detail',
    },
    {
      title: 'Unique Accounts',
      invertCompareTo: 'true',
      query: {
        nrql: `SELECT uniqueCount(${USER_IDENTIFIER}) as 'result' FROM ${VIDEO_EVENTS} `,
        lookup: 'result',
      },
      detailDashboardId: 'Audience-Plays-Detail',
    },
    {
      title: 'Unique Devices',
      invertCompareTo: 'true',
      query: {
        nrql: `SELECT uniquecount(deviceUuid) as 'result' FROM ${VIDEO_EVENTS} `,
        lookup: 'result',
      },
      detailDashboardId: 'Audience-Plays-Detail',
    },
  ],
  overviewDashboard: [
    {
      nrql: `SELECT count(*) as 'result' FROM ${VIDEO_EVENTS} where actionName = 'CONTENT_REQUEST' TIMESERIES `,
      columnStart: 1,
      columnEnd: 12,
      chartSize: 'micro',
      chartType: 'line',
      title: 'Play Attempts',
      useSince: true,
    },
    {
      nrql: `SELECT count(*) as 'Plays' FROM ${VIDEO_EVENTS} where actionName = 'CONTENT_START' TIMESERIES `,
      columnStart: 1,
      columnEnd: 6,
      chartSize: 'micro',
      chartType: 'line',
      title: 'Plays Trend',
      useSince: true,
    },
    {
      nrql: `SELECT uniquecount(viewId) as 'result' FROM ${VIDEO_EVENTS} where PageAction.actionName NOT IN ('PLAYER_READY') AND totalPlaytime > 1000 TIMESERIES `,
      columnStart: 7,
      columnEnd: 12,
      chartSize: 'micro',
      chartType: 'line',
      title: 'Peak Concurrent Plays Trend',
      useSince: true,
    },
    {
      nrql: `SELECT uniqueCount(${USER_IDENTIFIER}) as 'result' FROM ${VIDEO_EVENTS} TIMESERIES `,
      columnStart: 1,
      columnEnd: 6,
      chartSize: 'micro',
      chartType: 'line',
      title: 'Unique Accounts Trend',
      useSince: true,
    },
    {
      nrql: `SELECT uniquecount(deviceUuid) as 'result' FROM ${VIDEO_EVENTS} TIMESERIES `,
      columnStart: 7,
      columnEnd: 12,
      chartSize: 'micro',
      chartType: 'line',
      title: 'Unique Devices Trend',
      useSince: true,
    },
  ],
  detailDashboards: [
    {
      id: 'Audience-Plays-Detail',
      config: [
        {
          nrql: `SELECT uniqueCount(${USER_IDENTIFIER}) as 'Accounts' FROM ${VIDEO_EVENTS} `,
          columnStart: 1,
          columnEnd: 4,
          chartSize: 'small',
          chartType: 'billboard',
          title: 'Unique Accounts',
          useSince: true,
        },
        {
          nrql: `SELECT uniquecount(deviceUuid) as 'Devices' FROM ${VIDEO_EVENTS} `,
          columnStart: 5,
          columnEnd: 8,
          chartSize: 'small',
          chartType: 'billboard',
          title: 'Unique Devices',
          useSince: true,
        },
        {
          nrql: `SELECT uniqueCount(viewId) as 'View Ids' FROM ${VIDEO_EVENTS} where PageAction.actionName NOT IN ('PLAYER_READY') AND totalPlaytime > 0 `,
          columnStart: 9,
          columnEnd: 12,
          chartSize: 'small',
          chartType: 'billboard',
          title: 'Total Streams',
          useSince: true,
        },
        {
          nrql: `SELECT sum(playtimeSinceLastEvent)/60000 as 'Minutes' from ${VIDEO_EVENTS} `,
          columnStart: 1,
          columnEnd: 4,
          chartSize: 'small',
          chartType: 'billboard',
          title: 'Total Playtime',
          useSince: true,
        },
        {
          nrql: `SELECT (sum(playtimeSinceLastEvent)/60000)/uniqueCount(${USER_IDENTIFIER}) as 'Minutes' from ${VIDEO_EVENTS} `,
          columnStart: 5,
          columnEnd: 8,
          chartSize: 'small',
          chartType: 'billboard',
          title: 'Avg Minutes Per Account',
          useSince: true,
        },
        {
          nrql: `SELECT (sum(playtimeSinceLastEvent)/60000)/uniqueCount(deviceUuid) as 'Minutes' from ${VIDEO_EVENTS} `,
          columnStart: 9,
          columnEnd: 12,
          chartSize: 'small',
          chartType: 'billboard',
          title: 'Avg Minutes Per Device',
          useSince: true,
        },
        {
          nrql: `SELECT uniqueCount(viewId) as 'View Ids' FROM ${VIDEO_EVENTS} where PageAction.actionName NOT IN ('PLAYER_READY') AND totalPlaytime > 1000 FACET weekdayOf(timestamp) SINCE 1 week ago `,
          noFacet: true,
          columnStart: 1,
          columnEnd: 3,
          chartSize: 'small',
          chartType: 'bar',
          title: 'Avg Minutes Past Week',
          useSince: false,
        },
        {
          nrql: `SELECT uniqueCount(viewId) as 'View Ids' FROM ${VIDEO_EVENTS} where PageAction.actionName NOT IN ('PLAYER_READY') AND totalPlaytime > 1000 TIMESERIES `,
          columnStart: 4,
          columnEnd: 8,
          chartSize: 'small',
          chartType: 'area',
          title: 'Peak Concurrent Plays Trend',
          useSince: true,
        },
        {
          nrql: `SELECT sum(playtimeSinceLastEvent)/60000 as 'Minutes' from ${VIDEO_EVENTS}  TIMESERIES `,
          columnStart: 9,
          columnEnd: 12,
          chartSize: 'small',
          chartType: 'area',
          title: 'Total Playtime Trend',
          useSince: true,
        },
        {
          nrql: `FROM ${VIDEO_EVENTS} SELECT filter(uniqueCount(viewId), where PageAction.actionName NOT IN ('PLAYER_READY'))/uniqueCount(deviceUuid) as 'Avg Streams' WHERE totalPlaytime > 1000 `,
          columnStart: 1,
          columnEnd: 3,
          chartSize: 'small',
          chartType: 'billboard',
          title: 'Avg Streams Per Device',
          useSince: true,
        },
        {
          nrql: `SELECT uniqueCount(${USER_IDENTIFIER}) as 'Accounts' FROM ${VIDEO_EVENTS} TIMESERIES `,
          columnStart: 4,
          columnEnd: 8,
          chartSize: 'small',
          chartType: 'area',
          title: 'Unique Accounts Trend',
          useSince: true,
        },
        {
          nrql: `SELECT uniqueCount(deviceUuid) as 'Devices' FROM ${VIDEO_EVENTS} TIMESERIES `,
          columnStart: 9,
          columnEnd: 12,
          chartSize: 'small',
          chartType: 'area',
          title: 'Unique Devices Trend',
          useSince: true,
        },
      ],
    },
    {
      id: 'Audience-Devices-Detail',
      config: [],
    },
  ],
}
