import { USER_IDENTIFIER, VIDEO_EVENTS } from './constants'

const defaultToOne = metric => {
  return metric !== undefined ? metric : 1
}

export default {
  title: 'Video',
  eventTypes: [
    {
      event: 'Global',
      attributes: [
        ['appName', 'Platform'],
        ['playerVersion', 'Player'],
        ['playerName', 'Player'],
        ['contentSrc', 'Content'],
        ['countryCode', 'Geography'],
        ['contentIsLive', 'Content'],
        ['contentTitle', 'Content'],
      ],
    },
    {
      event: 'PageAction',
      eventSelector: { attribute: 'Delivery Type', value: 'Web' },
      attributes: [
        ['userAgentName', 'Platform'],
        ['userAgentOS', 'Platform'],
        ['userAgentVersion', 'Platform'],
        ['isAd', 'Content'],
        ['asnOrganization', 'Geography'],
        ['city', 'Geography'],
        ['regionCode', 'Geography'],
        ['message', 'Error'],
      ],
    },
    {
      event: 'MobileVideo',
      eventSelector: { attribute: 'Delivery Type', value: 'Mobile' },
      attributes: [
        ['isAd', 'Content'],
        ['asnOrganization', 'Geography'],
        ['city', 'Geography'],
        ['regionCode', 'Geography'],
        ['device', 'Platform'],
        ['deviceGroup', 'Platform'],
        ['deviceType', 'Platform'],
        ['osName', 'Platform'],
        ['osVersion', 'Platform'],
        ['message', 'Error'],
      ],
    },
    {
      event: 'RokuVideo',
      eventSelector: { attribute: 'Delivery Type', value: 'OTT' },
      attributes: [
        ['device', 'Platform'],
        ['deviceGroup', 'Platform'],
        ['deviceType', 'Platform'],
        ['osName', 'Platform'],
        ['osVersion', 'Platform'],
        ['errorMessage', 'Error'],
      ],
    },
    {
      event: 'BrowserVideo',
      eventSelector: { attribute: 'Delivery Type', value: 'Web' },
      attributes: [
        ['userAgentName', 'Platform'],
        ['userAgentOS', 'Platform'],
        ['userAgentVersion', 'Platform'],
        ['isAd', 'Content'],
        // ['asnOrganization', 'Geography'],
        // ['city', 'Geography'],
        // ['regionCode', 'Geography'],
        ['message', 'Error'],
      ],
    },
  ],
  metrics: [
    {
      id: 'VST',
      title: 'Video Start Time',
      threshold: {
        critical: 4,
        warning: 3.5,
      },
      query: {
        nrql: `FROM ${VIDEO_EVENTS} SELECT filter(percentile(timeSinceRequested/1000, 50), WHERE actionName = 'CONTENT_START') - filter(percentile(timeSinceAdBreakBegin/1000, 50), where actionName = 'AD_BREAK_END' and adPosition = 'pre') as 'percentile' `,
        lookup: 'percentile',
        title: 'Video Start Time (Avg)',
      },
      findUser: {
        nrql: `FROM ${VIDEO_EVENTS} SELECT (clamp_min(filter(sum(timeSinceRequested/1000), WHERE actionName = 'CONTENT_START'), 0) - clamp_min(filter(sum(timeSinceAdBreakBegin/1000), where actionName = 'AD_BREAK_END' and adPosition = 'pre'), 0))/filter(uniqueCount(viewId), where actionName='CONTENT_START') as 'result' `,
        lookup: 'result',
      },
      qualityScoreStrategy: 'clampMinZeroMaxOne',
      detailDashboardId: 'VST-Detail',
    },
    {
      id: 'CRR',
      title: 'Connection Buffering Ratio',
      threshold: {
        critical: 2.12,
        warning: 2,
      },
      query: {
        nrql: `FROM ${VIDEO_EVENTS} SELECT (filter(sum(timeSinceBufferBegin), where bufferType = 'connection' and timeSinceStarted > 10000 and actionName = 'CONTENT_BUFFER_END') - filter(sum(timeSinceBufferBegin), where bufferType = 'connection' and timeSinceStarted > 10000 and (timeSinceResumed < 10000 or timeSinceSeekEnd < 10000 or isBackground = 'true') and actionName = 'CONTENT_BUFFER_END')) / (filter(sum(timeSinceBufferBegin), where bufferType = 'connection' and timeSinceStarted > 10000 and actionName = 'CONTENT_BUFFER_END') - filter(sum(timeSinceBufferBegin), where bufferType = 'connection' and timeSinceStarted > 10000 and (timeSinceResumed < 10000 or timeSinceSeekEnd < 10000 or isBackground = 'true') and actionName = 'CONTENT_BUFFER_END') + sum(playtimeSinceLastEvent)) * 100 as 'result' `,
        lookup: 'result',
      },
      qualityScoreStrategy: 'clampMinZeroMaxOne',
      detailDashboardId: 'Buffering-Detail',
    },
    {
      id: 'CBT',
      title: 'Total Connection Buffering Time',
      query: {
        nrql: `FROM ${VIDEO_EVENTS} SELECT filter(sum(timeSinceBufferBegin/1000), WHERE actionName = 'CONTENT_BUFFER_END' AND bufferType = 'connection' and timeSinceStarted > 10000) - filter(sum(timeSinceBufferBegin/1000), where bufferType = 'connection' and timeSinceStarted > 10000 and (timeSinceResumed < 10000 or timeSinceSeekEnd < 10000 or isBackground = 'true')) as 'result' `,
        lookup: 'result',
      },
      detailDashboardId: 'Buffering-Detail',
    },
    {
      id: 'VSF',
      title: 'Video Start Failures',
      threshold: {
        critical: 100,
        warning: 50,
      },
      query: {
        nrql: `FROM ${VIDEO_EVENTS} SELECT filter(uniqueCount(viewId), where actionName = 'CONTENT_ERROR' and totalPlaytime < 1000) as 'result' `,
        lookup: 'result',
      },
      qualityScoreStrategy: 'zeroOrOne',
      detailDashboardId: 'VSF-Detail',
    },
    {
      id: 'ER',
      title: 'Video Playback Failures',
      threshold: {
        critical: 0.15,
        warning: 0.1,
      },
      query: {
        nrql: `FROM ${VIDEO_EVENTS} SELECT uniqueCount(viewId) as 'result' WHERE actionName = 'CONTENT_ERROR'and totalPlaytime >= 1000 `,
        lookup: 'result',
      },
      findUser: {
        nrql: `FROM ${VIDEO_EVENTS} SELECT filter(clamp_max(count(*), 1), where actionName = 'CONTENT_ERROR' and totalPlaytime >= 1000) / filter(clamp_max(count(*), 1), where actionName = 'CONTENT_REQUEST') * 100 as 'result' `,
        lookup: 'result',
      },
      qualityScoreStrategy: 'clampMinZeroMaxOne',
      detailDashboardId: 'ER-Detail',
    },
    {
      id: 'BR',
      title: 'Average Bitrate (mbps)',
      threshold: {
        critical: 4,
        warning: 4.5,
        type: 'below',
      },
      invertCompareTo: 'true',
      query: {
        nrql: `FROM ${VIDEO_EVENTS} SELECT average(contentBitrate)/1000000 as 'result' where contentBitrate is not null and actionName like 'CONTENT%' `,
        lookup: 'result',
      },
      detailDashboardId: 'BR-Detail',
    },
    // {
    //   id: 'CI',
    //   title: 'Interruption Rate',
    //   threshold: {
    //     critical: 23,
    //     warning: 20,
    //   },
    //   query: {
    //     nrql: `FROM ${VIDEO_EVENTS} SELECT filter(count(*), WHERE actionName = 'CONTENT_BUFFER_START' and bufferType = 'connection') / filter(count(*), WHERE actionName IN ('CONTENT_START', 'CONTENT_NEXT')) as 'result'`,
    //     lookup: 'result',
    //   },
    //   qualityScoreStrategy: 'clampMinZeroMaxOne',
    //   detailDashboardId: 'CI-Detail',
    // },
  ],
  overviewDashboard: [
    {
      nrql: `SELECT filter(average(timeSinceRequested)/1000, WHERE actionName='CONTENT_START') as 'seconds' FROM ${VIDEO_EVENTS} TIMESERIES `,
      columnStart: 1,
      columnEnd: 4,
      chartSize: 'small',
      chartType: 'line',
      title: 'Video Start Time Trend',
      useSince: true,
    },
    {
      nrql: `FROM ${VIDEO_EVENTS} SELECT uniqueCount(viewId) as 'Views' where actionName = 'CONTENT_ERROR' and totalPlaytime < 1000 TIMESERIES `,
      columnStart: 5,
      columnEnd: 8,
      chartSize: 'small',
      chartType: 'line',
      title: 'Video Start Failure Trend',
      useSince: true,
    },
    {
      nrql: `FROM ${VIDEO_EVENTS} SELECT uniqueCount(viewId) as 'Views' where actionName = 'CONTENT_ERROR' and totalPlaytime > 1000 TIMESERIES `,
      columnStart: 9,
      columnEnd: 12,
      chartSize: 'small',
      chartType: 'line',
      title: 'Video Playback Failure Trend',
      useSince: true,
    },
    {
      nrql: `FROM ${VIDEO_EVENTS} SELECT (filter(sum(timeSinceBufferBegin), where bufferType = 'connection' and timeSinceStarted > 10000 and actionName = 'CONTENT_BUFFER_END') - filter(sum(timeSinceBufferBegin), where bufferType = 'connection' and timeSinceStarted > 10000 and (timeSinceResumed < 10000 or timeSinceSeekEnd < 10000 or isBackground = 'true') and actionName = 'CONTENT_BUFFER_END')) / (filter(sum(timeSinceBufferBegin), where bufferType = 'connection' and timeSinceStarted > 10000 and actionName = 'CONTENT_BUFFER_END') - filter(sum(timeSinceBufferBegin), where bufferType = 'connection' and timeSinceStarted > 10000 and (timeSinceResumed < 10000 or timeSinceSeekEnd < 10000 or isBackground = 'true') and actionName = 'CONTENT_BUFFER_END') + sum(playtimeSinceLastEvent)) * 100 as '%' TIMESERIES `,
      columnStart: 1,
      columnEnd: 6,
      chartSize: 'small',
      chartType: 'line',
      title: 'Connection Buffering Ratio Trend',
      useSince: true,
    },
    {
      nrql: `SELECT uniqueCount(viewId) as 'Active Plays' FROM ${VIDEO_EVENTS} where totalPlaytime > 1000 TIMESERIES `,
      columnStart: 7,
      columnEnd: 12,
      chartSize: 'small',
      chartType: 'line',
      title: 'Plays Trend',
      useSince: true,
    },
    {
      nrql: `SELECT filter(average(timeSinceRequested)/1000, WHERE actionName='CONTENT_START') as 'seconds' FROM ${VIDEO_EVENTS} TIMESERIES `,
      facets: 'appName',
      columnStart: 1,
      columnEnd: 4,
      chartSize: 'small',
      chartType: 'area',
      title: 'Video Start Time Trend by App',
      useSince: true,
    },
    {
      nrql: `SELECT filter(average(timeSinceRequested)/1000, WHERE actionName='CONTENT_START') as 'seconds' FROM ${VIDEO_EVENTS} TIMESERIES `,
      facets: 'city, regionCode',
      columnStart: 5,
      columnEnd: 8,
      chartSize: 'small',
      chartType: 'area',
      title: 'Video Start Time Trend by City/Region Code',
      useSince: true,
    },
    {
      nrql: `SELECT filter(average(timeSinceRequested)/1000, WHERE actionName='CONTENT_START') as 'seconds' FROM ${VIDEO_EVENTS} TIMESERIES `,
      facets: 'asnOrganization, asnOwner',
      columnStart: 9,
      columnEnd: 12,
      chartSize: 'small',
      chartType: 'area',
      title: 'Video Start Time Trend by ISP Org/Owner',
      useSince: true,
    },
    {
      nrql: `FROM ${VIDEO_EVENTS} SELECT uniqueCount(viewId) as 'Views' where actionName = 'CONTENT_ERROR' and totalPlaytime < 1000 TIMESERIES `,
      facets: 'appName',
      columnStart: 1,
      columnEnd: 4,
      chartSize: 'small',
      chartType: 'area',
      title: 'Video Start Failure Trend by App',
      useSince: true,
    },
    {
      nrql: `FROM ${VIDEO_EVENTS} SELECT uniqueCount(viewId) as 'Views' where actionName = 'CONTENT_ERROR' and totalPlaytime < 1000 TIMESERIES `,
      facets: 'city,regionCode',
      columnStart: 5,
      columnEnd: 8,
      chartSize: 'small',
      chartType: 'area',
      title: 'Video Start Failure Trend by City/Region Code',
      useSince: true,
    },
    {
      nrql: `FROM ${VIDEO_EVENTS} SELECT uniqueCount(viewId) as 'Views' where actionName = 'CONTENT_ERROR' and totalPlaytime < 1000 TIMESERIES `,
      facets: 'asnOrganization, asnOwner',
      columnStart: 9,
      columnEnd: 12,
      chartSize: 'small',
      chartType: 'area',
      title: 'Video Start Failure Trend by ISP Org/Owner',
      useSince: true,
    },
    {
      nrql: `FROM ${VIDEO_EVENTS} SELECT uniqueCount(viewId) as 'Views' where actionName = 'CONTENT_ERROR' and totalPlaytime > 1000 TIMESERIES `,
      facets: 'appName',
      columnStart: 1,
      columnEnd: 4,
      chartSize: 'small',
      chartType: 'area',
      title: 'Video Playback Failure Trend by App',
      useSince: true,
    },
    {
      nrql: `FROM ${VIDEO_EVENTS} SELECT uniqueCount(viewId) as 'Views' where actionName = 'CONTENT_ERROR' and totalPlaytime > 1000 TIMESERIES `,
      facets: 'city,regionCode',
      columnStart: 5,
      columnEnd: 8,
      chartSize: 'small',
      chartType: 'area',
      title: 'Video Playback Failure Trend by City/Region Code',
      useSince: true,
    },
    {
      nrql: `FROM ${VIDEO_EVENTS} SELECT uniqueCount(viewId) as 'Views' where actionName = 'CONTENT_ERROR' and totalPlaytime > 1000 TIMESERIES `,
      facets: 'asnOrganization,asnOwner',
      columnStart: 9,
      columnEnd: 12,
      chartSize: 'small',
      chartType: 'area',
      title: 'Video Playback Failure Trend by ISP Org/Owner',
      useSince: true,
    },
    {
      nrql: `FROM ${VIDEO_EVENTS} SELECT (filter(sum(timeSinceBufferBegin), where bufferType = 'connection' and timeSinceStarted > 10000 and actionName = 'CONTENT_BUFFER_END') - filter(sum(timeSinceBufferBegin), where bufferType = 'connection' and timeSinceStarted > 10000 and (timeSinceResumed < 10000 or timeSinceSeekEnd < 10000 or isBackground = 'true') and actionName = 'CONTENT_BUFFER_END')) / (filter(sum(timeSinceBufferBegin), where bufferType = 'connection' and timeSinceStarted > 10000 and actionName = 'CONTENT_BUFFER_END') - filter(sum(timeSinceBufferBegin), where bufferType = 'connection' and timeSinceStarted > 10000 and (timeSinceResumed < 10000 or timeSinceSeekEnd < 10000 or isBackground = 'true') and actionName = 'CONTENT_BUFFER_END') + sum(playtimeSinceLastEvent)) * 100 as '%' TIMESERIES `,
      facets: 'appName',
      columnStart: 1,
      columnEnd: 4,
      chartSize: 'small',
      chartType: 'area',
      title: 'Connection Buffering Ratio Trend by App',
      useSince: true,
    },
    {
      nrql: `FROM ${VIDEO_EVENTS} SELECT (filter(sum(timeSinceBufferBegin), where bufferType = 'connection' and timeSinceStarted > 10000 and actionName = 'CONTENT_BUFFER_END') - filter(sum(timeSinceBufferBegin), where bufferType = 'connection' and timeSinceStarted > 10000 and (timeSinceResumed < 10000 or timeSinceSeekEnd < 10000 or isBackground = 'true') and actionName = 'CONTENT_BUFFER_END')) / (filter(sum(timeSinceBufferBegin), where bufferType = 'connection' and timeSinceStarted > 10000 and actionName = 'CONTENT_BUFFER_END') - filter(sum(timeSinceBufferBegin), where bufferType = 'connection' and timeSinceStarted > 10000 and (timeSinceResumed < 10000 or timeSinceSeekEnd < 10000 or isBackground = 'true') and actionName = 'CONTENT_BUFFER_END') + sum(playtimeSinceLastEvent)) * 100 as '%' TIMESERIES `,
      facets: 'city, regionCode',
      columnStart: 5,
      columnEnd: 8,
      chartSize: 'small',
      chartType: 'area',
      title: 'Connection Buffering Ratio Trend by City/Region Code',
      useSince: true,
    },
    {
      nrql: `FROM ${VIDEO_EVENTS} SELECT (filter(sum(timeSinceBufferBegin), where bufferType = 'connection' and timeSinceStarted > 10000 and actionName = 'CONTENT_BUFFER_END') - filter(sum(timeSinceBufferBegin), where bufferType = 'connection' and timeSinceStarted > 10000 and (timeSinceResumed < 10000 or timeSinceSeekEnd < 10000 or isBackground = 'true') and actionName = 'CONTENT_BUFFER_END')) / (filter(sum(timeSinceBufferBegin), where bufferType = 'connection' and timeSinceStarted > 10000 and actionName = 'CONTENT_BUFFER_END') - filter(sum(timeSinceBufferBegin), where bufferType = 'connection' and timeSinceStarted > 10000 and (timeSinceResumed < 10000 or timeSinceSeekEnd < 10000 or isBackground = 'true') and actionName = 'CONTENT_BUFFER_END') + sum(playtimeSinceLastEvent)) * 100 as '%' TIMESERIES `,
      facets: 'asnOrganization, asnOwner',
      columnStart: 9,
      columnEnd: 12,
      chartSize: 'small',
      chartType: 'area',
      title: 'Connection Buffering Ratio Trend by ISP Org/Owner',
      useSince: true,
    },
    {
      nrql: `SELECT uniqueCount(viewId) as 'Active Plays' FROM ${VIDEO_EVENTS} where totalPlaytime > 1000 TIMESERIES `,
      facets: 'appName',
      columnStart: 1,
      columnEnd: 4,
      chartSize: 'small',
      chartType: 'area',
      title: 'Plays Trend by App',
      useSince: true,
    },
    {
      nrql: `SELECT uniqueCount(viewId) as 'Active Plays' FROM ${VIDEO_EVENTS} where totalPlaytime > 1000 TIMESERIES `,
      facets: 'city,regionCode',
      columnStart: 5,
      columnEnd: 8,
      chartSize: 'small',
      chartType: 'area',
      title: 'Plays Trend by City/Region Code',
      useSince: true,
    },
    {
      nrql: `SELECT uniqueCount(viewId) as 'Active Plays' FROM ${VIDEO_EVENTS} where totalPlaytime > 1000 TIMESERIES `,
      facets: 'asnOrganization,asnOwner',
      columnStart: 9,
      columnEnd: 12,
      chartSize: 'small',
      chartType: 'area',
      title: 'Plays Trend by ISP Org/Owner',
      useSince: true,
    },
  ],
  detailDashboards: [
    {
      id: 'VSF-Detail',
      config: [
        {
          nrql: `FROM ${VIDEO_EVENTS} SELECT count(*) as 'Attempts'where actionName = 'CONTENT_REQUEST' `,
          columnStart: 1,
          columnEnd: 3,
          chartSize: 'small',
          chartType: 'billboard',
          title: 'Play Attempts',
          useSince: true,
        },
        {
          nrql: `FROM ${VIDEO_EVENTS} SELECT (filter(uniqueCount(viewId), where actionName = 'CONTENT_ERROR' AND totalPlaytime < 1000) / filter(count(*), where actionName = 'CONTENT_REQUEST')) *100 as '%' `,
          columnStart: 4,
          columnEnd: 6,
          chartSize: 'small',
          chartType: 'billboard',
          title: 'VSF %',
          useSince: true,
        },
        {
          nrql: `FROM ${VIDEO_EVENTS} SELECT count(*) as 'Attempts' where actionName = 'CONTENT_REQUEST' TIMESERIES `,
          columnStart: 7,
          columnEnd: 12,
          chartSize: 'small',
          chartType: 'area',
          title: 'Play Attempts Trend',
          useSince: true,
        },
        {
          nrql: `FROM ${VIDEO_EVENTS} SELECT filter(uniqueCount(${USER_IDENTIFIER}), where actionName = 'CONTENT_ERROR' and totalPlaytime < 1000) as '' `,
          columnStart: 1,
          columnEnd: 4,
          chartSize: 'small',
          chartType: 'billboard',
          title: 'VSF Customer Impact',
          useSince: true,
        },
        {
          nrql: `FROM ${VIDEO_EVENTS} SELECT filter(uniqueCount(${USER_IDENTIFIER}), where actionName = 'CONTENT_ERROR' and totalPlaytime < 1000) as 'Start Failures' TIMESERIES `,
          columnStart: 5,
          columnEnd: 12,
          chartSize: 'small',
          chartType: 'area',
          title: 'VSF Customer Impact Trend',
          useSince: true,
        },
        {
          nrql: `FROM ${VIDEO_EVENTS} SELECT uniqueCount(viewId) where totalPlaytime < 1000 `,
          facets: 'message',
          columnStart: 1,
          columnEnd: 7,
          chartSize: 'small',
          chartType: 'bar',
          title: 'Top Start Failure Messages',
          useSince: true,
        },
        {
          nrql: `FROM ${VIDEO_EVENTS} SELECT uniqueCount(viewId) where actionName = 'CONTENT_ERROR' and totalPlaytime < 1000 facet viewId LIMIT 200`,
          noFacet: 'true',
          columnStart: 8,
          columnEnd: 12,
          chartSize: 'small',
          chartType: 'bar',
          title: 'Failures by viewId (Click for details)',
          useSince: true,
          click: 'openSession',
        },
        {
          nrql: `FROM ${VIDEO_EVENTS} SELECT * where actionName != 'CONTENT_HEARTBEAT' LIMIT 1000`,
          noFacet: 'true',
          columnStart: 1,
          columnEnd: 5,
          chartSize: 'medium',
          chartType: 'table',
          title: 'Latest Events Log',
          useSince: true,
        },
        {
          nrql: `FROM ${VIDEO_EVENTS} SELECT actionName, appName, appVersion, city, regionCode, asnOrganization, asnOwner, deviceModel, osName, osVersion, playerName, playerVersion, userAgentOS, userAgentName where actionName = 'CONTENT_ERROR' and totalPlaytime < 1000 LIMIT MAX`,
          noFacet: 'true',
          columnStart: 6,
          columnEnd: 12,
          chartSize: 'medium',
          chartType: 'table',
          title: 'Start Failure Errors Log',
          useSince: true,
        },
      ],
    },
    {
      id: 'ER-Detail',
      config: [
        {
          nrql: `SELECT count(*) as 'Plays' FROM ${VIDEO_EVENTS} where actionName = 'CONTENT_START' `,
          columnStart: 1,
          columnEnd: 3,
          chartSize: 'small',
          chartType: 'billboard',
          title: 'Plays',
          useSince: true,
        },
        {
          nrql: `FROM ${VIDEO_EVENTS} SELECT (filter(uniqueCount(viewId), where actionName = 'CONTENT_ERROR' AND totalPlaytime > 1000) / filter(count(*), where actionName = 'CONTENT_START')) * 100 as '%' `,
          columnStart: 4,
          columnEnd: 6,
          chartSize: 'small',
          chartType: 'billboard',
          title: 'VPF %',
          useSince: true,
        },
        {
          nrql: `SELECT uniqueCount(viewId) as 'Active Plays' FROM ${VIDEO_EVENTS} where totalPlaytime > 1000 TIMESERIES `,
          columnStart: 7,
          columnEnd: 12,
          chartSize: 'small',
          chartType: 'area',
          title: 'Plays Trend',
          useSince: true,
        },
        {
          nrql: `FROM ${VIDEO_EVENTS} SELECT filter(uniqueCount(${USER_IDENTIFIER}), where actionName = 'CONTENT_ERROR' and totalPlaytime > 1000) as '' `,
          columnStart: 1,
          columnEnd: 3,
          chartSize: 'small',
          chartType: 'billboard',
          title: 'VSF Impacted Customers',
          useSince: true,
        },
        {
          nrql: `FROM ${VIDEO_EVENTS} SELECT filter(uniqueCount(viewId), where actionName = 'CONTENT_ERROR' and totalPlaytime > 1000) as'Playback Failures' TIMESERIES `,
          columnStart: 4,
          columnEnd: 12,
          chartSize: 'small',
          chartType: 'area',
          title: 'Playback Failure Trend',
          useSince: true,
        },
        {
          nrql: `FROM ${VIDEO_EVENTS} SELECT (filter(uniqueCount(viewId), where actionName = 'CONTENT_ERROR' AND totalPlaytime > 1000) / filter(count(*), where actionName = 'CONTENT_START')) *100 as '%' TIMESERIES `,
          columnStart: 1,
          columnEnd: 6,
          chartSize: 'small',
          chartType: 'area',
          title: 'VPF % Trend',
          useSince: true,
        },
        {
          nrql: `FROM ${VIDEO_EVENTS} SELECT filter(uniqueCount(${USER_IDENTIFIER}), where actionName = 'CONTENT_ERROR' and totalPlaytime > 1000) as'Playback Failures' TIMESERIES `,
          columnStart: 7,
          columnEnd: 12,
          chartSize: 'small',
          chartType: 'area',
          title: 'Customer Impact Trend',
          useSince: true,
        },
        {
          nrql: `FROM ${VIDEO_EVENTS} SELECT count(*) where actionName = 'CONTENT_ERROR' and totalPlaytime > 1000 facet viewId LIMIT 200`,
          noFacet: true,
          columnStart: 1,
          columnEnd: 12,
          chartSize: 'small',
          chartType: 'bar',
          title: 'Playback Failure by viewId (Click for details)',
          useSince: true,
          click: 'openSession',
        },
        {
          nrql: `FROM ${VIDEO_EVENTS} SELECT * where actionName != 'CONTENT_HEARTBEAT' LIMIT 1000`,
          noFacet: 'true',
          columnStart: 1,
          columnEnd: 5,
          chartSize: 'medium',
          chartType: 'table',
          title: 'Latest Events Log',
          useSince: true,
        },
        {
          nrql: `FROM ${VIDEO_EVENTS} SELECT actionName, appName, appVersion, city, regionCode, asnOrganization, asnOwner, deviceModel, osName, osVersion, playerName, playerVersion, userAgentOS, userAgentName where actionName = 'CONTENT_ERROR' and totalPlaytime > 1000 LIMIT MAX`,
          noFacet: 'true',
          columnStart: 6,
          columnEnd: 12,
          chartSize: 'medium',
          chartType: 'table',
          title: 'Latest Errors Log',
          useSince: true,
        },
      ],
    },
    {
      id: 'VST-Detail',
      config: [
        {
          nrql: `SELECT filter(uniqueCount(viewId), WHERE timeSinceRequested > 4000 and actionName = 'CONTENT_START')/uniqueCount(viewId) * 100 as '%' FROM ${VIDEO_EVENTS} `,
          columnStart: 1,
          columnEnd: 3,
          chartSize: 'small',
          chartType: 'billboard',
          title: 'Views above Threshold (4s)',
          useSince: true,
        },
        {
          nrql: `SELECT filter(sum(timeSinceRequested)/1000, WHERE actionName = 'CONTENT_START') - filter(sum(timeSinceAdBreakBegin)/1000, where actionName = 'AD_BREAK_END' and adPosition = 'pre') as 'Time To First Frame (Average)' FROM ${VIDEO_EVENTS} FACET viewId LIMIT 25`,
          noFacet: true,
          columnStart: 4,
          columnEnd: 12,
          chartSize: 'small',
          chartType: 'bar',
          title: 'Views, Average Video Start Time (Click for details)',
          useSince: true,
          click: 'openSession',
        },
        {
          nrql: `FROM ${VIDEO_EVENTS} SELECT filter(percentile(timeSinceRequested/1000, 50), WHERE actionName = 'CONTENT_START') - filter(percentile(timeSinceAdBreakBegin/1000, 50), where actionName = 'AD_BREAK_END' and adPosition = 'pre') as '50th Percentile' `,
          columnStart: 1,
          columnEnd: 3,
          chartSize: 'small',
          chartType: 'billboard',
          title: 'Video Start Time',
          useSince: true,
        },
        {
          nrql: `FROM ${VIDEO_EVENTS} SELECT filter(percentile(timeSinceRequested/1000, 50), WHERE actionName = 'CONTENT_START') - filter(percentile(timeSinceAdBreakBegin/1000, 50), where actionName = 'AD_BREAK_END' and adPosition = 'pre') as '50th Percentile' TIMESERIES MAX `,
          facets: 'deviceType',
          columnStart: 4,
          columnEnd: 12,
          chartSize: 'small',
          chartType: 'area',
          title: 'Video Start Time ',
          useSince: true,
        },
        {
          nrql: `FROM ${VIDEO_EVENTS} SELECT percentile(timeSinceLoad, 50) as 'seconds' WHERE actionName = 'CONTENT_START' `,
          columnStart: 1,
          columnEnd: 3,
          chartSize: 'small',
          chartType: 'billboard',
          title: 'Video Start Time - With Ads',
          useSince: true,
        },
        {
          nrql: `FROM ${VIDEO_EVENTS} SELECT percentile(timeSinceLoad, 50) as 'seconds' WHERE actionName = 'CONTENT_START' TIMESERIES MAX `,
          facets: 'deviceType',
          columnStart: 4,
          columnEnd: 12,
          chartSize: 'small',
          chartType: 'area',
          title: 'Video Start Time - With Ads',
          useSince: true,
        },
        {
          nrql: `FROM ${VIDEO_EVENTS} SELECT percentile(timeSinceRequested/1000,50) as 'seconds' where actionName = 'AD_START' and adPosition = 'pre'`,
          columnStart: 1,
          columnEnd: 3,
          chartSize: 'small',
          chartType: 'billboard',
          title: 'Video Start Time - Pre Roll Ad',
          useSince: true,
        },
        {
          nrql: `FROM ${VIDEO_EVENTS} SELECT percentile(timeSinceRequested/1000,50) as 'seconds' where actionName = 'AD_START' and adPosition = 'pre' TIMESERIES MAX `,
          facets: 'deviceType',
          columnStart: 4,
          columnEnd: 12,
          chartSize: 'small',
          chartType: 'area',
          title: 'Video Start Time - Pre Roll Ad',
          useSince: true,
        },
      ],
    },
    {
      id: 'Buffering-Detail',
      config: [
        {
          nrql: `SELECT count(*) as 'Plays' FROM ${VIDEO_EVENTS} where actionName = 'CONTENT_START' `,
          columnStart: 1,
          columnEnd: 3,
          chartSize: 'small',
          chartType: 'billboard',
          title: 'Plays',
          useSince: true,
        },
        {
          nrql: `FROM ${VIDEO_EVENTS} SELECT filter(uniquecount(viewId), where bufferType = 'connection' and timeSinceStarted > 10000 AND (timeSinceResumed IS NULL or timeSinceResumed > 10000 or timeSinceSeekEnd is NULL or timeSinceSeekEnd > 10000 or isBackground = 'false')) / filter(uniquecount(viewId), where totalPlaytime > 1000) * 100 as '%' `,
          columnStart: 4,
          columnEnd: 6,
          chartSize: 'small',
          chartType: 'billboard',
          title: '% Plays with CIRR',
          useSince: true,
        },
        {
          nrql: `SELECT uniqueCount(viewId) as 'Active Plays' FROM ${VIDEO_EVENTS} where totalPlaytime > 1000 TIMESERIES `,
          columnStart: 7,
          columnEnd: 12,
          chartSize: 'small',
          chartType: 'area',
          title: 'Plays Trend',
          useSince: true,
        },
        {
          nrql: `FROM ${VIDEO_EVENTS} SELECT uniquecount(${USER_IDENTIFIER}) as '' where bufferType = 'connection' and timeSinceStarted > 10000 AND (timeSinceResumed IS NULL or timeSinceResumed > 10000 or timeSinceSeekEnd is NULL or timeSinceSeekEnd > 10000 or isBackground = 'false') `,
          columnStart: 1,
          columnEnd: 3,
          chartSize: 'small',
          chartType: 'billboard',
          title: 'CIRR Total Customers Impacted',
          useSince: true,
        },
        {
          nrql: `FROM ${VIDEO_EVENTS} SELECT percentage(uniquecount(${USER_IDENTIFIER}), where bufferType = 'connection' and timeSinceStarted > 10000 AND (timeSinceResumed IS NULL or timeSinceResumed > 10000 or timeSinceSeekEnd is NULL or timeSinceSeekEnd > 10000 or isBackground = 'false')) as '%' `,
          columnStart: 4,
          columnEnd: 6,
          chartSize: 'small',
          chartType: 'billboard',
          title: 'CIRR % Customers Impacted',
          useSince: true,
        },
        {
          nrql: `FROM ${VIDEO_EVENTS} SELECT (filter(sum(timeSinceBufferBegin), where bufferType = 'connection' and timeSinceStarted > 10000 and actionName = 'CONTENT_BUFFER_END') - filter(sum(timeSinceBufferBegin), where bufferType = 'connection' and timeSinceStarted > 10000 and (timeSinceResumed < 10000 or timeSinceSeekEnd < 10000 or isBackground = 'true') and actionName = 'CONTENT_BUFFER_END')) / (filter(sum(timeSinceBufferBegin), where bufferType = 'connection' and timeSinceStarted > 10000 and actionName = 'CONTENT_BUFFER_END') - filter(sum(timeSinceBufferBegin), where bufferType = 'connection' and timeSinceStarted > 10000 and (timeSinceResumed < 10000 or timeSinceSeekEnd < 10000 or isBackground = 'true') and actionName = 'CONTENT_BUFFER_END') + sum(playtimeSinceLastEvent)) * 100 as '%' TIMESERIES `,
          columnStart: 7,
          columnEnd: 12,
          chartSize: 'small',
          chartType: 'area',
          title: 'CIRR Trend',
          useSince: true,
        },
        {
          nrql: `FROM ${VIDEO_EVENTS} SELECT filter(uniquecount(viewId), where bufferType = 'connection' and timeSinceStarted > 10000 AND (timeSinceResumed IS NULL or timeSinceResumed > 10000 or timeSinceSeekEnd is NULL or timeSinceSeekEnd > 10000 or isBackground = 'false')) / filter(uniquecount(viewId), where totalPlaytime > 1000) * 100 as '%' TIMESERIES `,
          columnStart: 1,
          columnEnd: 4,
          chartSize: 'small',
          chartType: 'area',
          title: '% Plays with CIRR',
          useSince: true,
        },
        {
          nrql: `FROM ${VIDEO_EVENTS} SELECT uniquecount(${USER_IDENTIFIER}) as 'Impacted Customers' where bufferType = 'connection' and timeSinceStarted > 10000 AND (timeSinceResumed IS NULL or timeSinceResumed > 10000 or timeSinceSeekEnd is NULL or timeSinceSeekEnd > 10000 or isBackground = 'false')  TIMESERIES `,
          columnStart: 5,
          columnEnd: 8,
          chartSize: 'small',
          chartType: 'area',
          title: 'CIRR Total Customer Impact Trend',
          useSince: true,
        },
        {
          nrql: `FROM ${VIDEO_EVENTS} SELECT percentage(uniquecount(${USER_IDENTIFIER}), where bufferType = 'connection' and timeSinceStarted > 10000 AND (timeSinceResumed IS NULL or timeSinceResumed > 10000 or timeSinceSeekEnd is NULL or timeSinceSeekEnd > 10000 or isBackground = 'false')) as '%' TIMESERIES `,
          columnStart: 9,
          columnEnd: 12,
          chartSize: 'small',
          chartType: 'area',
          title: 'CIRR % Customers Impacted Trend',
          useSince: true,
        },
        {
          nrql: `FROM ${VIDEO_EVENTS} SELECT filter(count(*), WHERE actionName = 'CONTENT_BUFFER_END' AND bufferType = 'connection' and timeSinceStarted > 10000) - filter(count(*), WHERE actionName = 'CONTENT_BUFFER_END'AND bufferType = 'connection' and timeSinceStarted > 10000 and (timeSinceResumed < 10000 or timeSinceSeekEnd < 10000 or isBackground = 'true')) as 'Buffer Events' `,
          columnStart: 1,
          columnEnd: 3,
          chartSize: 'small',
          chartType: 'billboard',
          title: 'CIRR Events',
          useSince: true,
        },
        {
          nrql: `FROM ${VIDEO_EVENTS} SELECT filter(count(*), WHERE actionName = 'CONTENT_BUFFER_END' AND bufferType = 'connection' and timeSinceStarted > 10000) - filter(count(*), WHERE actionName = 'CONTENT_BUFFER_END'AND bufferType = 'connection' and timeSinceStarted > 10000 and (timeSinceResumed < 10000 or timeSinceSeekEnd < 10000 or isBackground = 'true')) as 'Buffer Events' TIMESERIES `,
          columnStart: 4,
          columnEnd: 8,
          chartSize: 'small',
          chartType: 'area',
          title: 'CIRR Events Trend',
          useSince: true,
        },
        {
          nrql: `FROM ${VIDEO_EVENTS} SELECT sum(timeSinceBufferBegin)/1000 as 'Total Buffering' WHERE actionName = 'CONTENT_BUFFER_END' and bufferType = 'connection' FACET viewId LIMIT 25 `,
          noFacet: true,
          columnStart: 9,
          columnEnd: 12,
          chartSize: 'small',
          chartType: 'bar',
          title: 'viewIds with high CIRR, Seconds (Click for details)',
          useSince: true,
          click: 'openSession',
        },
        {
          nrql: `FROM ${VIDEO_EVENTS} SELECT average(timeSinceBufferBegin/1000) as 'seconds' where actionName = 'CONTENT_BUFFER_END'and bufferType = 'connection' and timeSinceStarted > 10000 AND (timeSinceResumed > 10000 OR timeSinceResumed IS NULL) AND (timeSinceSeekEnd > 10000 OR timeSinceSeekEnd is NULL) AND isBackground != 'true' `,
          columnStart: 1,
          columnEnd: 3,
          chartSize: 'small',
          chartType: 'billboard',
          title: 'Average Buffer Length',
          useSince: true,
        },
        {
          nrql: `FROM ${VIDEO_EVENTS} SELECT average(timeSinceBufferBegin/1000) as 'seconds' where actionName = 'CONTENT_BUFFER_END'and bufferType = 'connection' and timeSinceStarted > 10000 AND (timeSinceResumed > 10000 OR timeSinceResumed IS NULL) AND (timeSinceSeekEnd > 10000 OR timeSinceSeekEnd is NULL) AND isBackground != 'true' TIMESERIES `,
          columnStart: 4,
          columnEnd: 8,
          chartSize: 'small',
          chartType: 'area',
          title: 'Average Buffer Length Trend',
          useSince: true,
        },
        {
          nrql: `FROM ${VIDEO_EVENTS} SELECT filter(sum(timeSinceBufferBegin/1000), WHERE actionName = 'CONTENT_BUFFER_END' AND bufferType = 'connection' and timeSinceStarted > 10000) - filter(sum(timeSinceBufferBegin/1000), where bufferType = 'connection' and timeSinceStarted > 10000 and (timeSinceResumed < 10000 or timeSinceSeekEnd < 10000 or isBackground = 'true')) as 'seconds' TIMESERIES `,
          columnStart: 9,
          columnEnd: 12,
          chartSize: 'small',
          chartType: 'area',
          title: 'Total Buffer Seconds Trend',
          useSince: true,
        },
        {
          nrql: `FROM ${VIDEO_EVENTS} SELECT * where actionName != 'CONTENT_HEARTBEAT' LIMIT 1000`,
          noFacet: 'true',
          columnStart: 1,
          columnEnd: 5,
          chartSize: 'medium',
          chartType: 'table',
          title: 'Latest Events Log',
          useSince: true,
        },
        {
          nrql: `FROM ${VIDEO_EVENTS} SELECT actionName, bufferType, timeSinceBufferBegin, timeSinceSeekEnd, timeSinceStarted, timeSinceResumed, appName, appVersion, city, regionCode, asnOrganization, asnOwner, deviceModel, osName, osVersion, playerName, playerVersion, userAgentOS, userAgentName where actionName = 'CONTENT_BUFFER_END'and bufferType = 'connection' and timeSinceStarted > 10000 AND (timeSinceResumed > 10000 OR timeSinceResumed IS NULL) AND (timeSinceSeekEnd > 10000 OR timeSinceSeekEnd is NULL) AND isBackground != 'true' LIMIT MAX`,
          noFacet: 'true',
          columnStart: 6,
          columnEnd: 12,
          chartSize: 'medium',
          chartType: 'table',
          title: 'Latest CIRR Events Log',
          useSince: true,
        },
      ],
    },
    {
      id: 'BR-Detail',
      config: [
        {
          nrql: `FROM ${VIDEO_EVENTS} SELECT average(contentBitrate)/1000000 as 'mbps' where contentBitrate is not null and actionName like 'CONTENT%' `,
          columnStart: 1,
          columnEnd: 4,
          chartSize: 'small',
          chartType: 'billboard',
          title: 'Avg Bitrate',
          useSince: true,
        },
        {
          nrql: `FROM ${VIDEO_EVENTS} SELECT average(contentBitrate)/1000000 as 'mbps' where contentBitrate is not null and actionName like 'CONTENT%' TIMESERIES `,
          columnStart: 5,
          columnEnd: 12,
          chartSize: 'small',
          chartType: 'area',
          title: 'Bitrate Trend',
          useSince: true,
        },
        {
          nrql: `FROM ${VIDEO_EVENTS} SELECT average(contentBitrate)/1000000 as 'mbps' where contentBitrate is not null and actionName like 'CONTENT%' `,
          facets: 'appName',
          columnStart: 1,
          columnEnd: 4,
          chartSize: 'small',
          chartType: 'billboard',
          title: 'Avg Bitrate by App',
          useSince: true,
        },
        {
          nrql: `FROM ${VIDEO_EVENTS} SELECT average(contentBitrate)/1000000 as 'mbps' where contentBitrate is not null and actionName like 'CONTENT%' TIMESERIES `,
          facets: 'appName',
          columnStart: 5,
          columnEnd: 12,
          chartSize: 'small',
          chartType: 'area',
          title: 'Bitrate Trend by App',
          useSince: true,
        },
        {
          nrql: `FROM ${VIDEO_EVENTS} SELECT percentile(contentBitrate, 50)/1000000 as 'Bitrate', percentile(contentBitrate, 90)/1000000 as 'Bitrate', percentile(contentBitrate, 95)/1000000 as 'Bitrate', percentile(contentBitrate, 99)/1000000 as 'Bitrate' where contentBitrate is not null and actionName like 'CONTENT%' `,
          noFacet: true,
          columnStart: 1,
          columnEnd: 4,
          chartSize: 'small',
          chartType: 'billboard',
          title: 'Bitrate Percentile',
          useSince: true,
        },
        {
          nrql: `FROM ${VIDEO_EVENTS} SELECT percentile(contentBitrate, 50)/1000000 as 'Bitrate', percentile(contentBitrate, 90)/1000000 as 'Bitrate', percentile(contentBitrate, 95)/1000000 as 'Bitrate', percentile(contentBitrate, 99)/1000000 as 'Bitrate' where contentBitrate is not null and actionName like 'CONTENT%' TIMESERIES MAX `,
          columnStart: 5,
          columnEnd: 12,
          chartSize: 'small',
          chartType: 'area',
          title: 'Bitrate Percentile Trend',
          useSince: true,
        },
        {
          nrql: `FROM ${VIDEO_EVENTS} SELECT average(contentBitrate)/1000000 as 'mbps' where contentBitrate is not null and actionName like 'CONTENT%' facet viewId LIMIT 200 `,
          noFacet: true,
          columnStart: 1,
          columnEnd: 12,
          chartSize: 'small',
          chartType: 'bar',
          title: 'Lowest Average Bitrate by viewId (Click for details)',
          useSince: true,
          click: 'openSession',
        },
      ],
    },
    {
      id: 'CI-Detail',
      config: [
        {
          nrql: `FROM ${VIDEO_EVENTS} SELECT filter(uniqueCount(viewId), WHERE actionName = 'CONTENT_BUFFER_START' and bufferType = 'connection') / filter(uniqueCount(viewId), WHERE actionName IN ('CONTENT_START', 'CONTENT_NEXT')) * 100 as '%' `,
          columnStart: 1,
          columnEnd: 3,
          chartSize: 'small',
          chartType: 'billboard',
          title: 'Views above Threshold (23%)',
          useSince: true,
        },
        {
          nrql: `FROM ${VIDEO_EVENTS} SELECT count(*) WHERE actionName = 'CONTENT_BUFFER_START' and bufferType = 'connection' FACET viewId LIMIT 25 `,
          noFacet: true,
          columnStart: 4,
          columnEnd: 12,
          chartSize: 'small',
          chartType: 'bar',
          title: 'Views with Interruptions (Click for details)',
          useSince: true,
          click: 'openSession',
        },
        {
          nrql: `FROM ${VIDEO_EVENTS} SELECT filter(count(*), WHERE actionName = 'CONTENT_BUFFER_START' and bufferType = 'connection') / filter(count(*), WHERE actionName IN ('CONTENT_START', 'CONTENT_NEXT')) * 100 as '%' `,
          columnStart: 1,
          columnEnd: 3,
          chartSize: 'small',
          chartType: 'billboard',
          title: 'Interruption Rate',
          useSince: true,
        },
        {
          nrql: `FROM ${VIDEO_EVENTS} SELECT filter(count(*), WHERE actionName = 'CONTENT_BUFFER_START' and bufferType = 'connection') / filter(count(*), WHERE actionName IN ('CONTENT_START', 'CONTENT_NEXT')) * 100 as '%' timeseries MAX `,
          facets: `deviceType`,
          columnStart: 4,
          columnEnd: 12,
          chartSize: 'small',
          chartType: 'scatter',
          title: 'Interruption Rate',
          useSince: true,
        },
      ],
    },
  ],
  qualityScore: {
    include: ['VSF', 'VST', 'CRR', 'ER'],
    formula: metrics => {
      const vsf = defaultToOne(metrics.VSF)
      const rest =
        (defaultToOne(metrics.VST) +
          1 + // defaultToOne(metrics.CI) +
          defaultToOne(metrics.CRR) +
          defaultToOne(metrics.ER)) *
        25
      return vsf * rest
    },
    threshold: {
      critical: 80,
      warning: 90,
      type: 'below',
    },
  },
}
